### ISSUE TITLE
Alias multiple emails to a single user.

### ISSUE THREAD

**Issue by derekcollison** [n1try/gitcount#4]
Great project! Be nice to have a small config file that would allow aliasing multiple emails to a single author. Also be great to have #1 as well.

**Comment by muety** [comment]
Good idea. I'd suggest a simple YAML or JSON config file. Either it maps a user's "main" email address to a list of aliases, which should be considered for the same user, while the output will show only the main address. Alternatively, a custom "user name" could be specified, which is then referenced in the output. What do you think?

### Option 1
```
{
   "user1@a.com": [ "user1@b.com", "user_1@c.com" ],
   ...
}
```

### Option 2
```
[
  {
    "key": "User 1",
    "aliases":  [ "user1@a.com", "user1@b.com", "user_1@c.com" ]
  }, 
  ...
]
```

**Comment by derekcollison** [comment]
CNCF has something that does this when they do reporting etc.

**Comment by bhavin192** [comment]
This would be interesting to work on, once we decide between two options I will work on it.

**Comment by derekcollison** [comment]
Sounds great. Thanks..

**Comment by gonzalesraul** [comment]
Hi,  Check that out PR #6.

Git already have this native, I just created a reader so that we could use it on the app.
https://git-scm.com/docs/git-check-mailmap

Also, you might find interest this command `git shortlog -sne`, it will show a list with commit count per each user, and it uses the `.mailmap` file :grimacing:
